language: php
php:
- 5.5
env:
- DB=mysql
- BD=pgsql


before_install: 
  - sudo apt-get update -q
  - sudo apt-get install ruby-full -y
  - gem install sass


install: ./install-dependencies.sh

#before_script: true

script: 
  - phpunit Test.php

after_success: true

before_deploy: true

deploy: true

after_deploy: true

after_script: true

notifications:
  irc: "irc.freenode.org#yourfavouriteroomfortravis"
