language: php

dist: xenial

php:
- 7.0

env:
- BD=pgsql


script: 
- phpunit Test.php
- phpunit WebTest.php

notifications:
  email:
    - diegocarrera2000@gmail.com
  irc: "irc.freenode.org#yourfavouriteroomfortravis"
