language: php
dist: xenial
php:
- 7.0
env:
- BD=pgsql

before_install:
- sudo apt-get update -q
- sudo apt-get install phpunit -y

before_script: true

script: 
- phpunit Test.php
- phpunit WebTest.php

notifications:
  email:
    - diegocarrera2000@gmail.com
  irc: "irc.freenode.org#yourfavouriteroomfortravis"
